# ---- Backend (Warnetix-App) ----
[services.warnetix-app]
root = "."
dockerfilePath = "deploy/Dockerfile.backend"

# ---- Frontend (zonal-balance) ----
[services.zonal-balance]
root = "."
dockerfilePath = "Dockerfile"