app = "warnetix-backend"
primary_region = "sin"

[build]
  dockerfile = "deploy/Dockerfile.backend"
[env]
  ENV = "production"
  SCAN_MAX_MB = "100"
  POLICY_DEFAULT = "simulate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
