[project]
name = "warnetix"

[services.backend]
name = "backend"
source = "."
dockerfile = "deploy/Dockerfile.backend"
healthcheckPath = "/health"
env = { ENV="production", SCAN_MAX_MB="100", POLICY_DEFAULT="simulate" }

[services.worker]
name = "worker"
source = "."
dockerfile = "deploy/Dockerfile.worker"
env = { ENV="production", SCAN_MAX_MB="100" }

[plugins]
redis = { serviceName="redis" }
